"""Generate, save and validate plant-level data for a French maize field."""

from pathlib import Path
from pprint import pformat
import math
import random


NUMERICAL_RANGES = {
    "plant_height_cm": (170, 310),
    "leaf_damage_percent": (0, 100),
    "moisture_sensor_percent": (0, 100),
    "ear_length_cm": (10, 28),
    "grain_mass_per_ear_g": (40, 300),
}
EXPECTED_COLUMNS = set(NUMERICAL_RANGES) | {"field_zone"}
VALID_FIELD_ZONES = {"Northwest", "Northeast", "Centre", "Southwest", "Southeast"}


def generate_maize_dataset(
    number_of_observations=600,
    seed=42,
    output_filename="data_tools_output_synthetic.py",
):
    """Generate reproducible maize observations and save them to a Python file.

    Args:
        number_of_observations: Number of plant observations to create.
        seed: Starting value for the private random-number generator. Reusing the
            same seed and observation count produces the same dataset.
        output_filename: Name of the Python file written beside this module.

    Returns:
        A dictionary whose keys are sample IDs and whose values are dictionaries
        containing five numerical features and one categorical variable.
    """
    random_generator = random.Random(seed)
    field_zones = ["Northwest", "Northeast", "Centre", "Southwest", "Southeast"]
    dataset = {}

    for observation_number in range(1, number_of_observations + 1):
        # Approximately symmetric distribution around 240 cm.
        plant_height_cm = random_generator.gauss(240, 18)

        # Right-skewed distribution: many low values and a few high values.
        leaf_damage_percent = random_generator.lognormvariate(0.7, 0.9)

        # Almost constant values representing a poorly calibrated sensor.
        moisture_sensor_percent = random_generator.gauss(18, 0.005)

        ear_length_cm = random_generator.gauss(19, 2)

        # Grain mass increases with ear length, with natural random variation.
        grain_mass_per_ear_g = (ear_length_cm * 8.5) + random_generator.gauss(0, 12)

        observation_id = f"sample_{observation_number:03d}"
        dataset[observation_id] = {
            "plant_height_cm": round(max(170, min(310, plant_height_cm)), 2),
            "leaf_damage_percent": round(min(100, leaf_damage_percent), 2),
            "moisture_sensor_percent": round(moisture_sensor_percent, 3),
            "ear_length_cm": round(max(10, min(28, ear_length_cm)), 2),
            "grain_mass_per_ear_g": round(max(40, grain_mass_per_ear_g), 2),
            "field_zone": random_generator.choice(field_zones),
        }

    save_maize_dataset(
        dataset,
        output_filename,
        "Synthetic maize harvest data generated by data_tools.py.",
    )

    return dataset


def save_maize_dataset(dataset, output_filename, description):
    """Save a maize dictionary in an importable Python file.

    The generated file defines the dataset as ``maize_harvest_data``. Importing
    ``nan`` allows a deliberately corrupted test dataset to preserve NaN values
    while still remaining a valid Python file.

    Args:
        dataset: Dictionary of maize observations to save.
        output_filename: Name of the output file written beside this module.
        description: Short module docstring placed at the top of the output.
    """
    output_path = Path(__file__).resolve().parent / output_filename
    output_text = f'"""{description}"""\n\n'
    output_text += "from math import nan\n\n"
    output_text += "maize_harvest_data = " + pformat(dataset, sort_dicts=False, width=100) + "\n"
    output_path.write_text(output_text, encoding="utf-8")


def check_data_integrity(dataset, dataset_name="dataset in memory"):
    """Check the structure and values of a maize dataset.

    The function assumes a dictionary-of-dictionaries structure, five numerical
    features and one categorical variable, the expected column names, types and
    ranges, and unique sample IDs and observations.

    It deliberately does not check whether the sampling locations are spatially
    representative or whether the dataset is scientifically true. It checks
    data integrity only.

    Args:
        dataset: The dictionary-of-dictionaries to inspect.
        dataset_name: File name or other short label included in the printed
            summary so the user knows which dataset was checked.

    Returns:
        A report dictionary containing the validity result, observation count,
        detailed errors and warnings. The function also prints a clear summary.
    """
    report = {
        "valid": True,
        "dataset_name": dataset_name,
        "observation_count": 0,
        "errors": [],
        "warnings": [],
    }

    def count_error(code, message, sample_id=None, field=None):
        """Record one detected problem for inclusion in the final error count.

        Each call creates a consistently structured error entry and appends it
        to ``report["errors"]``. The function does not create or modify errors
        in the dataset; it only records problems found by the integrity checks.
        """
        error = {"code": code, "message": message}
        if sample_id is not None:
            error["sample_id"] = sample_id
        if field is not None:
            error["field"] = field
        report["errors"].append(error)

    if not isinstance(dataset, dict):
        count_error("invalid_dataset_type", "The dataset must be a dictionary.")
    else:
        report["observation_count"] = len(dataset)
        previously_seen_observations = {}

        for sample_id, observation in dataset.items():
            if not isinstance(sample_id, str):
                count_error("invalid_sample_id", "The sample ID must be a string.", sample_id)

            if not isinstance(observation, dict):
                count_error(
                    "invalid_observation_type",
                    "The observation must be a dictionary.",
                    sample_id,
                )
                continue

            missing_columns = EXPECTED_COLUMNS - set(observation)
            unexpected_columns = set(observation) - EXPECTED_COLUMNS

            for field in sorted(missing_columns):
                count_error("missing_column", f"Missing required column: {field}.", sample_id, field)

            for field in sorted(unexpected_columns):
                count_error("unexpected_column", f"Unexpected column: {field}.", sample_id, field)

            for field, (minimum, maximum) in NUMERICAL_RANGES.items():
                if field not in observation:
                    continue

                value = observation[field]
                if isinstance(value, bool) or not isinstance(value, (int, float)):
                    count_error("invalid_type", "Expected a numerical value.", sample_id, field)
                elif not math.isfinite(value):
                    count_error("non_finite_value", "The value must be finite.", sample_id, field)
                elif not minimum <= value <= maximum:
                    count_error(
                        "out_of_range",
                        f"The value must be between {minimum} and {maximum}.",
                        sample_id,
                        field,
                    )

            if "field_zone" in observation:
                field_zone = observation["field_zone"]
                if not isinstance(field_zone, str):
                    count_error("invalid_type", "The field zone must be text.", sample_id, "field_zone")
                elif field_zone not in VALID_FIELD_ZONES:
                    count_error(
                        "invalid_category",
                        f"Unknown field zone: {field_zone}.",
                        sample_id,
                        "field_zone",
                    )

            observation_signature = tuple(
                (field, repr(observation.get(field))) for field in sorted(EXPECTED_COLUMNS)
            )
            if observation_signature in previously_seen_observations:
                original_id = previously_seen_observations[observation_signature]
                count_error(
                    "duplicate_observation",
                    f"This observation duplicates {original_id}.",
                    sample_id,
                )
            else:
                previously_seen_observations[observation_signature] = sample_id

    report["valid"] = len(report["errors"]) == 0
    if report["valid"]:
        print(
            f"Data integrity check passed: {report['observation_count']} valid observations. "
            f"File checked: {dataset_name}"
        )
    else:
        problem_count = len(report["errors"])
        noun = "problem" if problem_count == 1 else "problems"
        print(
            f"Data integrity check failed: {problem_count} {noun} found. "
            f"File checked: {dataset_name}"
        )

    return report


if __name__ == "__main__":
    generate_maize_dataset()

